fieldLayouts:
  ce56c3fe-479f-4091-8f21-5c1c77daade7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: e4106e24-2997-4d86-b82c-305273ffeafc # received_welcome
            instructions: ''
            label: ' '
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d6085f2e-5a8f-46a5-bd52-08658fa9fc14 # Freeze
            instructions: ''
            label: Freeze
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f41d9808-f911-483e-b548-90f6a5227850 # Members
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Members
        sortOrder: 2
handle: workspace
name: workspace
siteSettings:
  e7ddbb89-e989-43d1-86e9-e9e4f45da062: # alerti
    hasUrls: true
    template: index
    uriFormat: 'w/{slug}'
structure:
  maxLevels: 1
  uid: 2e2e161a-3d44-47df-b326-f27acc2c8da5
