fieldLayouts:
  fb5dcfc1-3689-459e-8153-836e4904f98b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: myAlertiApp
hasUrls: false
name: my-alerti-app
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: my-alerti-app-dev
  bucketSelectionMode: manual
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $S3_KEY
  makeUploadsPublic: '1'
  region: us-east-1
  secret: $S3_SECRET
  storageClass: ''
  subfolder: ''
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\awss3\Volume
url: ''
