contentColumnType: text
fieldGroup: 601a3482-84dc-49e0-b997-fda3e0696dc3 # app
handle: appname
instructions: ''
name: 'App Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
