dateModified: 1623773931
email:
  fromEmail: aminembarki@gmail.com
  fromName: alerti
  transportType: craft\mail\transportadapters\Sendmail
system:
  edition: pro
  live: true
  name: alerti
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
