dateModified: 1623852268
email:
  fromEmail: aminembarki@gmail.com
  fromName: alerti
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  auth0:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: alerti
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
