dateModified: 1624865482
email:
  fromEmail: aminembarki@gmail.com
  fromName: alerti
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  auth0:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: PED0LL8EK7L28QQ0PLZAQBQO
    schemaVersion: 1.0.21
system:
  edition: pro
  live: true
  name: alerti
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
