enableVersioning: true
handle: board
name: board
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e7ddbb89-e989-43d1-86e9-e9e4f45da062: # alerti
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
